version: '2.2'
services:
  test_elasticsearch_9999:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - cluster.name=docker-test-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=true
      # make sure it works on nearly full disk
      - cluster.routing.allocation.disk.watermark.low=3gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=1gb
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      # give our test instance a port number that is for sure not going to write to some poor cluster listening on 9200
      - 9999:9200
